--Granting security admin role to an specific user
GRANT ROLE "SECURITYADMIN" TO USER X;

--Change role
USE ROLE SECURITYADMIN;

--Creating Quantil users
CREATE USER KERENLOPEZ
    PASSWORD = 'password'
    LOGIN_NAME = 'KERENLOPEZ'
    EMAIL = 'kerenlopezcordoba@quantil.com.co'
    COMMENT = 'this is a user of quantil'
    MUST_CHANGE_PASSWORD = TRUE;

--Creating role QUANTIL_TEAM
CREATE ROLE "QUANTIL_TEAM" COMMENT = "This is a specific role for the members of the quantil team";
GRANT ROLE "QUANTIL_TEAM" TO ROLE "SYSADMIN";
--Assigning role
GRANT ROLE "QUANTIL_TEAM" TO USER X;
GRANT ROLE "QUANTIL_TEAM" TO USER X;
GRANT ROLE "QUANTIL_TEAM" TO USER X;

--Creating role ANALIST_TEAM
CREATE ROLE "ANALIST_TEAM" comment = "This is a specific role for members of ProColombia's analytics team";
GRANT ROLE "ANALIST_TEAM" TO ROLE "SYSADMIN";
--Assigning role
GRANT ROLE "ANALIST_TEAM" TO USER X;
GRANT ROLE "ANALIST_TEAM" TO USER X;
GRANT ROLE "ANALIST_TEAM" TO USER X;

--Granting privilegies to QUANTIL_TEAM role
GRANT ALL PRIVILEGES ON WAREHOUSE X TO ROLE "QUANTIL_TEAM";
SHOW GRANTS ON WAREHOUSE X;

GRANT USAGE ON DATABASE X to role "QUANTIL_TEAM";
SHOW GRANTS ON DATABASE X;

GRANT ALL PRIVILEGES ON SCHEMA X to role "QUANTIL_TEAM";
SHOW GRANTS ON SCHEMA X;

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA X TO ROLE "QUANTIL_TEAM";
SHOW GRANTS ON TABLE X;

--Granting privilegies to ANALIST_TEAM role
GRANT ALL PRIVILEGES ON WAREHOUSE X TO ROLE "ANALIST_TEAM";
SHOW GRANTS ON WAREHOUSE X;

GRANT USAGE ON DATABASE X to role "ANALIST_TEAM";
SHOW GRANTS ON DATABASE X;

GRANT ALL PRIVILEGES ON SCHEMA X to role "ANALIST_TEAM";
SHOW GRANTS ON SCHEMA X;

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA X TO ROLE "ANALIST_TEAM";
SHOW GRANTS ON TABLE X;

