SELECT
    TAG_VALUE,
    SUM(NVL(CREDITS_USED, 0)) AS CREDITS
FROM
    SNOWFLAKE.ACCOUNT_USAGE.TAG_REFERENCES
LEFT JOIN
    SNOWFLAKE.ACCOUNT_USAGE.WAREHOUSE_METERING_HISTORY ON WAREHOUSE_NAME=OBJECT_NAME
WHERE
    TAG_NAME = 'DEPARTMENTS_TEST'
AND TAG_DATABASE = 'TAGGING_DB_TEST'
AND TAG_SCHEMA = 'TAGGING_SCH_TEST'
AND DOMAIN = 'WAREHOUSE'
AND START_TIME>=DATEADD('DAYS',-7,CURRENT_DATE())
GROUP BY 1
ORDER BY 2 DESC;