-- Store the count of tagged warehouses in a temporary table
CREATE OR REPLACE TEMPORARY TABLE TEMP_TAGGED_WAREHOUSES AS
SELECT 
    COUNT(DISTINCT OBJECT_NAME) AS TAGGED_WAREHOUSE_COUNT
FROM 
    SNOWFLAKE.ACCOUNT_USAGE.TAG_REFERENCES
WHERE 
    DOMAIN = 'WAREHOUSE';

-- Retrieve all warehouses and store the count in a temporary table
SHOW WAREHOUSES;

-- Create a temporary table to hold the count of warehouses
CREATE OR REPLACE TEMPORARY TABLE TEMP_TOTAL_WAREHOUSES AS
SELECT COUNT(*) AS TOTAL_WAREHOUSES
FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()));

-- Calculate the difference between total warehouses and tagged warehouses
SELECT 
    (SELECT TAGGED_WAREHOUSE_COUNT FROM TEMP_TAGGED_WAREHOUSES) - 
    (SELECT TOTAL_WAREHOUSES FROM TEMP_TOTAL_WAREHOUSES) AS UNTAGGED_WAREHOUSE_COUNT;
