SELECT
    TAG_VALUE,
    ((AVERAGE_DATABASE_BYTES + AVERAGE_FAILSAFE_BYTES + AVERAGE_HYBRID_TABLE_STORAGE_BYTES)/POWER(1024,2))::NUMBER(8,2) AS TOTAL_MB
FROM
    SNOWFLAKE.ACCOUNT_USAGE.TAG_REFERENCES
LEFT JOIN
    SNOWFLAKE.ACCOUNT_USAGE.DATABASE_STORAGE_USAGE_HISTORY ON DATABASE_NAME = OBJECT_NAME
WHERE
    TAG_NAME = 'ENVIRONMENT_TEST'
AND TAG_DATABASE = 'TAGGING_DB_TEST'
AND TAG_SCHEMA = 'TAGGING_SCH_TEST'
AND DOMAIN = 'DATABASE'
AND OBJECT_NAME <> 'SNOWFLAKE'
AND DELETED IS NULL
AND USAGE_DATE>=DATEADD('DAYS', -7, CURRENT_DATE())
ORDER BY 2 DESC;